server:
  port: 9000

spring:
  application:
    name: gateway
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    gateway:
      default-filters:
        - TokenRelay=
      routes:
        - id: backend-route
          uri: http://localhost:8080
          predicates:
            - Path=/api/**
  security:
    oauth2:
      client:
        registration:
#          google:
#            client-id: 139185455381-3j26uipc2lvtu671il2bru0dkk16m2jk.apps.googleusercontent.com
#            client-secret: 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
#            scope: openid,profile,email
          azure:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope: openid, ${BACKEND_SCOPE}
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/${TENANT_ID}/v2.0
            user-info-uri: https://login.microsoftonline.com/${TENANT_ID}/openid/v2.0/userinfo
logging:
  level:
    root: INFO