server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://login.microsoftonline.com/${TENANT_ID}/v2.0
          jwk-set-uri: https://login.microsoftonline.com/${TENANT_ID}/discovery/v2.0/keys


logging:
  level:
    root: INFO